# Blueprint for https://render.com
services:
  - type: web
    name: nest-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
